id: P11611277
initial_creation_type: input
source_metadata:
  title: Jamgön Kongtrul Lodrö Thaye Series
  language: fr
  description: Works by or about the great nineteenth century master Jamgön Kongtrul
    Lodrö Thaye ('jam mgon kong sprul blo gros mtha' yas, 1813–1899), one of the pioneers
    of the Rimé movement
  volume:
    021dd51e4b2947cb86ed1eb8a9322808:
      title: Advice to Lhawang Tashi
      parent: Advice
    74a9f97079db4fc0a0896f500fe38e32:
      title: Mahāmudrā Preliminaries, Main Part & Conclusion
      parent: Advice
    227ba27144024a6a8c1398b4c1202124:
      title: 'Mahāmudrā: the Swift Way to Become a Lord of Realization'
      parent: Advice
    41930bf2228942c1b2838d7799d2b3b7:
      title: The Kusāli's Instruction on the Nature of Mind
      parent: Advice
    bd1dd3274c284b9981790f587f51d46c:
      title: Prayer for Peace and Stability in Tibet
      parent: Aspiration Prayers
    0ce6cff6a18d42b3a0ef00000ac8dcf0:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Aspiration Prayers
    e565b5b1dca34ceaa45e821b968f1bf2:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Biography
    ee1633ad5c064136a0a12391c4e552d5:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    f1e08011dee34910b1b41a5bbd4c9c1c:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Biography
    a6af9b85f0844075940661163199f5e6:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Calling the Guru From Afar
    0082edc130074f6fb877ca5136eee7a2:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      parent: Commentaries
    fdb4a99f43e24863a4951cc3a45e6d57:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Empowerment Rites
    33bc6091d22f4bcaab8b78e62a4d614a:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Fire Offering
    15f64675c3b74e4cb7e971f528061d80:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Guru Rinpoche Prayers
    067fd45c035e44b69d87746c877df798:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Lineage Prayers
    2f0cd548ad1a4973bdd42721f81c94b8:
      title: A Short Supplication to Tārā
      parent: Prayers
    16b68f5bad274247acf934f67269b9b2:
      title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse
        Chökyi Lodrö
      parent: Prayers
    731e7717a7a94d939fd87b9d0d5d69da:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    167c028d7afc4a0e9ba3b8b48108a1a6:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Prayers
    1e2c54723587476799e3742e21e6391e:
      title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master
        Jamgön Kongtrul Thaye'
      parent: Prayers
    66a57a44781b459bb99c0154463d033a:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Prayers
    a5fc88ffc0d84055bc4c806518701215:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Saving Lives
    d1f31a9b1db74baf9edfea0ad1f50ea9:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Swift Rebirth Prayers
    8950b3a40835412a8e47948feb3154e0:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Tsok
    bf33d86a9969421380ac5b26c657c088:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T23:32:21.219536'
last_modified_at: '2022-02-28T23:32:21.219539'
